# This file is for continuous deployment with travis
language: generic 

# For supper user permissions
sudo: required

services: 
    # Install docker in to container
    - docker

# For a series of commands to run before test runs
before_install:
    # -t tags the docker-react repo with my username
    # NOTE we can tag using any name e.g. MY_IMAGE
    - docker build -t mubeji/docker-react -f Dockerfile.dev .
    # Build docker IMAGE using Dockerfile.dev


# The scripts section contains all commands to be executed
# to run on our test suit
script:
    - docker run -e CI=true mubeji/docker-react yarn run test

# Now deploy
deploy: 
    edge: true
    # elasticbeanstalk AWS
    provider: elasticbeanstalk
    # The region comes from the link on AWS 
    # DockerReact-env.vbptw2p9b3.us-east-2.elasticbeanstalk.com
    region: "us-east-2"
    # Name of the app
    app: "docker-react"

    env: "DockerReact-env"

    # This is a zip file that contains all the files for
    # the app
    bucket_name: "elasticbeanstalk-us-east-2-188785653063"

    # Use app name above
    bucket_path: "docker-react"

    # Only attempt to deploy the app when there's modifications 
    # to the master branch
    on:
        branch: master 

    # API keys to give travis ci access to our AWS account
    # From local environment varables
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"













